FROM n8nio/n8n:latest

RUN mkdir -p /home/node/files
VOLUME ["/home/node/files"]

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=changeme
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=changeme
ENV DB_POSTGRESDB_USER=changeme
ENV DB_POSTGRESDB_PASSWORD=changeme

ENV N8N_ENCRYPTION_KEY=changeme
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=changeme

EXPOSE 5678

ENTRYPOINT ["n8n"]
CMD ["start"]
