services:
  - type: web
    name: n8n
    env: node
    buildCommand: npm install
    startCommand: n8n
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "1234"
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        value: https://kylezz-creative.onrender.com
      - key: DB_TYPE
        value: "postgresdb"
